source 'https://rubygems.org'

gem 'rails',        '4.0.0'

gem 'cancan'
gem 'capistrano',   group: :development
gem 'carrierwave'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'high_voltage'
gem 'jbuilder',     '~> 1.2'
gem 'jquery-rails'
gem 'mysql2'
gem 'rails_admin'
gem 'rmagick'
gem 'sass-rails',   '~> 4.0.0'
gem 'simple_form'
gem 'turbolinks'
gem 'uglifier',     '>= 1.3.0'
gem 'unicorn'
